services:
  build-c-server:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: make
  dev:
    image: gcc:13
    volumes:
      - .:/app
    working_dir: /app
    command: make
