services:
  build-c-server:
    image: c-server:latest
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: make
  dev:
    image: gcc:13
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: make

  check:
    image: c-server:dev
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: [make, test]
