name: Check Code Integrity

on:
  - push
  - pull_request

jobs:
  build-and-lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang clang-format clang-tidy cppcheck make gcc check

      - name: Run clang-format
        run: |
          echo "Checking formatting..."
          clang-format --dry-run --Werror $(find src include tests -name '*.c' -o -name '*.h')

      - name: Run clang-tidy
        run: |
          echo "Running clang-tidy..."
          clang-tidy $(find src tests -name '*.c') -- -Iinclude

      - name: Run cppcheck
        run: |
          echo "Running cppcheck..."
          cppcheck --enable=all --error-exitcode=1 \
            --suppressions-list=.cppcheck-suppress \
            --inline-suppr \
            -Iinclude \
            src tests

      - name: Build project
        run: |
          echo "Building..."
          make

      - name: Run tests
        run: |
          echo "Running tests..."
          make test
